### ISSUE TITLE
Getting an Error

### ISSUE THREAD

**Issue by IRISDavidD** [uktrade/stream-read-xbrl#145]
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.

Any idea on a fix for this?

**Comment by michalc** [comment]
It might be that you're running code in the top level, and not inside a function. This gives an error like the one reportted:

```python
import datetime
from stream_read_xbrl import stream_read_xbrl_sync

with stream_read_xbrl_sync(datetime.date(2013, 8, 31)) as (columns, date_range_and_rows):
    for ((start_date, end_date), rows) in date_range_and_rows:
        print(start_date, end_date)
        for row in rows:
           pass
```

But this doesn't:

```python
import datetime
from stream_read_xbrl import stream_read_xbrl_sync

def main():
    with stream_read_xbrl_sync(datetime.date(2013, 8, 31)) as (columns, date_range_and_rows):
        for ((start_date, end_date), rows) in date_range_and_rows:
            print(start_date, end_date)
            for row in rows:
               pass

if __name__ == '__main__':
    main()
```
This is required due to multiprocessing behaviour that stream-read-xbrl uses under the hood.

If this doesn't solve it - can you post the code you're running, enough so we can reproduce the issue at our end? Ideally a [minimum reproducible example, StackOverflow-style](https://stackoverflow.com/help/minimal-reproducible-example)

This is admittedly not obvious from the docs at all - will see if can improve them.

**Comment by michalc** [comment]
Think this is explained by the change in docs. If no, feel free to re-open
